### ISSUE TITLE
Make it easy to run locally

### ISSUE THREAD

**Issue by AndersNS** [varianter/variant-live#2]
As the title says: Make it easier to run the visualizer locally

**Comment by mikaelbr** [comment]
Thanks for the suggestion. Yeah, this should be more stream lined. All the different parts are there, just not assembled. I'll look into this tonight and hopefully have something for you not too late. But if you want it/need it now, the simplest way would be to use the previewer: https://github.com/varianter/variant-live/tree/master/previewer

It's almost everything you need to run it locally. but instead of loading all visualisations (https://github.com/varianter/variant-live/blob/master/previewer/js/app.js#L3) you only render your own.

**Comment by AndersNS** [comment]
That worked. However Chrome blogs autoplaying audio by default, so I had to go to site settings for localhost:1234 and allow audio.

**Comment by mikaelbr** [comment]
I see. I think we'll just do it like that for now. I don't think it disallows autoplaying, but just autplaying without an user interaction first. But if it works for you by doing that, thats great! 👍 

I just pushed a folder `run-locally` with a file visualisation under js. You can run npm start from run-locally root and edit the code there. It didn't seem to work well with the parcel HMR I'm afraid. Would have to look into that some more, but I have to run for dinner now. Just ping me if there's something that is broken

**Comment by mikaelbr** [comment]
Added guide here: https://github.com/varianter/variant-live/blob/master/README.md#kj%C3%B8r-lokalt
